### ISSUE TITLE
Bad interpolation of diaeresis

### ISSUE THREAD

**Issue by dscorbett** [WCYS-Co/Hauora-Sans#21]
In version 1.001, the dots of the diaeresis partially overlap in some weights. It looks like an interpolation problem where the contour of the left dot in the bold master corresponds to the contour of the right dot in the light master. This affects the following:

* U+00A8 DIAERESIS
* U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
* U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS
* U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS
* U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
* U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS
* U+00E4 LATIN SMALL LETTER A WITH DIAERESIS
* U+00EB LATIN SMALL LETTER E WITH DIAERESIS
* U+00EF LATIN SMALL LETTER I WITH DIAERESIS
* U+00F6 LATIN SMALL LETTER O WITH DIAERESIS
* U+00FC LATIN SMALL LETTER U WITH DIAERESIS
* U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
* U+0178 LATIN CAPITAL LETTER Y WITH DIAERESIS
* U+03AA GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
* U+03AB GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
* U+03CA GREEK SMALL LETTER IOTA WITH DIALYTIKA
* U+03CB GREEK SMALL LETTER UPSILON WITH DIALYTIKA
* U+1E84 LATIN CAPITAL LETTER W WITH DIAERESIS
* U+1E85 LATIN SMALL LETTER W WITH DIAERESIS

**Comment by wayne-shih** [comment]
yeah some of the diacritic have gone haywire... think it's the export script I'm using. had a crack at it yesterday when I was fixing the `commaaccentcomb` disappearing issue, but ended up manually overriding the individual glyphs. 
@dscorbett btw what tool are ya using to inspect the font? seem to be able find them bugs faster than I can fix them 👀 😅

**Comment by dscorbett** [comment]
Nothing special: I’m just scrolling through the glyph set and lookups in FontForge. Some of the problems I’ve found are [reported upstream](https://github.com/sharanda/manrope/issues).

**Comment by wayne-shih** [comment]
long overdue... [v1.002](https://github.com/WCYS-Co/Hauora-Sans/releases/tag/v1.002) fixes this :)
