### ISSUE TITLE
Localized forms for different language systems in the same lookup

### ISSUE THREAD

**Issue by dscorbett** [WCYS-Co/Hauora-Sans#24]
The 'locl' substitution for Turkic languages (`i` → `i.loclTRK`) is in the same lookup as the 'locl' substitutions for Romanian (`Scedilla` → `uni0218` etc.). The lookup only has the language system tag 'ROM '. That means any text tagged as Romanian will also be localized as Turkish, and any text tagged as Turkish will not be localized.

Similarly, the 'locl' substitutions for Bulgarian and Serbian are mixed into the same lookup.

**Comment by wayne-shih** [comment]
hey @dscorbett this is a Glyphs export issue i think... the current v1.003 (and before) are all manually export via "File > Export" 

i'm in the process of adding fontmake scripts to this repo which should resolve this 

I did a test export via fontmake alongside a fontbakery report, here's the files if you need a fix urgently: 
[hauora-actions2-fonts (1).zip](https://github.com/WCYS-Co/Hauora-Sans/files/8813271/hauora-actions2-fonts.1.zip)

Looking at the locl on the new generated ttf file...

<img width="351" alt="CleanShot 2022-06-01 at 22 32 54@2x" src="https://user-images.githubusercontent.com/51947763/171385068-1caa5bde-5017-419d-9de7-ff44a5275a2f.png">  <img width="308" alt="CleanShot 2022-06-01 at 22 33 19@2x" src="https://user-images.githubusercontent.com/51947763/171385127-86fb7524-cddb-49b5-91b0-e2a40eb4434b.png">

... this should be good now right?

**Comment by dscorbett** [comment]
Yes, that fixes it.
